JENKINS-66921 fix
jenkinsci/xunit-plugin pull request #94
Opened 2022-05-06 12:57 UTC by mulawamichal

If the RUNNING (or FINISHED) node did not exist, it failed with below error:

> Conversion error: Invalid time "0" (hour must be two digits)

corrected default value for those items from 0 to '00:00:00'

https://issues.jenkins.io/browse/JENKINS-66921

tested manually by processing faulty valgrind reports (attached to above jira ticket) with https://www.freeformatter.com/xsl-transformer.html

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-05-06 14:05 UTC, nfalco79 requested changes

2022-05-06 14:06 UTC, nfalco79 commented
> Ensure you have provided tests - that demonstrates feature works or fixes the issue

i do not see additional test case. Please create more cases simply uploading you example file in 
src/test/resources/org/jenkinsci/plugins/xunit/types/valgrind/testcase3 and testcase4

2022-05-09 09:35 UTC, mulawamichal commented on src/main/resources/org/jenkinsci/plugins/xunit/types/valgrind-1.0-to-junit.xsl
> +        <xsl:variable name="startTime" select="xunit:millis-from-time(xunit:if-empty(substring(status/state[text() = 'RUNNING']/../time, 4), '00:00:00'))" />
cannot. apparently, this function wants 2 params:
https://github.com/jenkinsci/xunit-plugin/pull/94/checks?check_run_id=6349149827

2022-05-09 09:37 UTC, nfalco79 commented on src/main/resources/org/jenkinsci/plugins/xunit/types/valgrind-1.0-to-junit.xsl
> +        <xsl:variable name="startTime" select="xunit:millis-from-time(xunit:if-empty(substring(status/state[text() = 'RUNNING']/../time, 4), '00:00:00'))" />
I already tested in my local, millis-from-time want just one

2022-05-09 09:40 UTC, mulawamichal commented on src/main/resources/org/jenkinsci/plugins/xunit/types/valgrind-1.0-to-junit.xsl
> +        <xsl:variable name="startTime" select="xunit:millis-from-time(xunit:if-empty(substring(status/state[text() = 'RUNNING']/../time, 4), '00:00:00'))" />
?? tried it:
https://github.com/jenkinsci/xunit-plugin/pull/94/commits/cd5515e56390cbf3dd5a257db5e2af7a1426206f
it failed

2022-05-09 09:49 UTC, nfalco79 commented on src/main/resources/org/jenkinsci/plugins/xunit/types/valgrind-1.0-to-junit.xsl
> +        <xsl:variable name="startTime" select="xunit:millis-from-time(xunit:if-empty(substring(status/state[text() = 'RUNNING']/../time, 4), '00:00:00'))" />
Look this PR #95

2022-05-09 09:52 UTC, nfalco79 commented
> as i wrote previously - i tested this using the mentioned page, as there is not even a slightest mention in README of how to run tests in this project.

all maven project execute test with `mvn clean verify`

2022-05-09 10:01 UTC, mulawamichal commented on src/main/resources/org/jenkinsci/plugins/xunit/types/valgrind-1.0-to-junit.xsl
> +        <xsl:variable name="startTime" select="xunit:millis-from-time(xunit:if-empty(substring(status/state[text() = 'RUNNING']/../time, 4), '00:00:00'))" />
great to see it. i\ll close this one. just please use the "anonimized" version of the problematic xml file

2022-05-09 10:28 UTC, closed without merging

2022-05-09 10:28 UTC, nfalco79 commented
merged manually, thanks for the PR