Changed the summary text and the check title format.
jenkinsci/xunit-plugin pull request #97
Opened 2022-10-05 14:14 UTC by crenan

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Changed the summary text because in Gitea (that uses the Check Plugin) the summary is the title of the check (img below)

![image](https://user-images.githubusercontent.com/13079569/194081722-39a22991-b668-41d5-ac11-8ba43f3b0d25.png)

With this PR the summary text will be the same as the title.
I also changed the format of the title to _"total: X, failed: X, skipped: X, passed: X"_

2022-10-05 14:47 UTC, nfalco79 commented
do you have an image of this result?

2022-10-05 16:10 UTC, crenan commented
Hi @nfalco79. No, I don't.

2022-10-06 09:41 UTC, nfalco79 requested changes

2022-10-06 20:52 UTC, nfalco79 approved these changes

2022-10-06 20:55 UTC, merged